#!/usr/bin/perl -w

# $Id: filter,v 1.1 2006-03-28 18:31:53-08 kst Exp $
# $Source: /home/kst/gx-map-redacted/new-dns-2006-03-22/filter,v $

use strict;

#
# Comments refer to CVS revision numbers for
# tools/gx-map/new-dns-2006-03-22/dn_to_login_name.txt
#

while (<>) {
    my($dn, $user) = /^(.*) (\S*)$/;

    next if $dn !~ m(^/);		# 1.2
    next if $user eq '';		# 1.3
    next if $user eq 'U14831';		# 1.4
    $dn =~ s(/userid=)(/USERID=);	# 1.5
    next if $dn =~ m(/CN=proxy$);	# 1.6
    next if $dn eq '/C=US/O=Pittsburgh Supercomputing Center/OU=PSC Kerberos Certification'; # 1.7
    if ($dn eq '/C=US/O=SDSC/CN=Nicholas Wright') {
	$dn = '/C=US/O=SDSC/OU=SDSC/CN=Nicholas Wright/UID=nwright'; # 1.8, 1.10
    }
    next if $dn eq '/C=US/O=SDSC/OU=SDSC/CN=Tharaka Devadithya'; # 1.9
    print "$dn $user\n";
}
