#!/bin/sh

# $Id: _install,v 1.3 2004-10-11 17:45:21-07 kst Exp $
# $Source: /home/kst/gx-map-redacted/_install,v $

verbosely() {
    echo "% $@"
    "$@"
}

verbosely rm -rf /tmp/kst/apps/gx-map-0.4-alpha
verbosely rm -rf /tmp/kst/var/gx-map-0.4-alpha-data
verbosely rm -rf /tmp/kst/etc/grid-security
verbosely mkdir -p /tmp/kst/etc/grid-security/certificates
verbosely make clean
verbosely ./configure-gx-map kst-test.conf
verbosely make install clean
