#!/bin/sh

# $Id: _install,v 1.1 2004-09-28 20:08:45-07 kst Exp $
# $Source: /home/kst/gx-map-redacted/_install,v $

rm -rf /tmp/kst/apps/gx-map-0.4-alpha \
       /tmp/kst/var/gx-map-0.4-alpha-data \
       /tmp/kst/certificates
mkdir /tmp/kst/certificates
make clean
./configure-gx-map kst-test.conf
make install clean
