#!/bin/sh

# $Id: cleanup-gx-map,v 1.2 2003-07-09 20:54:57-07 kst Exp $
# $Source: /home/kst/gx-map-redacted/cleanup-gx-map,v $

for file in *.in cacl/*.in ; do
    target=`echo $file | sed 's/\.in$//'`
    if [ -f $target ] ; then
	echo "rm -f $target"
	rm -f $target
    fi
done
