#!/bin/sh

# $Id: cleanup-gx-map,v 1.7 2005-12-30 00:29:33-08 kst Exp $
# $Source: /home/kst/gx-map-redacted/cleanup-gx-map,v $

for file in *.in gx-propagate ; do
    target=`echo $file | sed 's/\.in$//'`
    if [ -f $target ] ; then
        echo "rm -f $target"
        rm -f $target
    fi
done

for file in doc/*.[1578] ; do
    if [ -f $file ] ; then
        echo "rm -f $file"
        rm -f $file
    fi
done

if [ -f .config-file ] ; then
    echo "rm -f .config-file"
    rm -f .config-file
fi
