#!/bin/sh

# $Id: cleanup-gx-map,v 1.4 2003-07-25 01:08:25-07 kst Exp $
# $Source: /home/kst/gx-map-redacted/cleanup-gx-map,v $

for file in *.in ; do
    target=`echo $file | sed 's/\.in$//'`
    if [ -f $target ] ; then
	echo "rm -f $target"
	rm -f $target
    fi
done
