#!/bin/sh

# $Id: install-personal-gx-map,v 1.5 2005-05-10 17:52:27-07 kst Exp $
# $Source: /home/kst/gx-map-redacted/install-personal-gx-map,v $

#
# Set up a gx-map test installation under the user's home directory.
#

try() {
    echo "% $@"
    eval "$@" || exit 1
}

die() {
    echo "$@" 1>&2
    exit 1
}

usage() {
    cat <<EOF
Usage: $0 [options] tarball
    -help      Display this message and exit
    -perl arg  Full path to Perl executable
               Default is $default_perl
    -path arg  Value for PATH
               Default is $default_path
"tarball" is a source tarball (*.tar.gz) for gx-map
EOF
    exit 1
}

########################################################################

default_perl=/usr/bin/perl
default_path=/bin:/usr/bin

perl=$default_perl
path=$default_path

while [ $# -gt 0 ] ; do
    case "$1" in
        -help)
            usage
            ;;
        -perl)
            shift
            if [ $# -eq 0 ] ; then
                die "-perl requires an argument (-help for usage)"
            fi
            perl=$1
            ;;
        -path)
            shift
            if [ $# -eq 0 ] ; then
                die "-path requires an argument (-help for usage)"
            fi
            path=$1
            ;;
        -*)
            die "Unrecognized option $1 (-help for usage)"
            ;;
        *.tar.gz)
            tarball=$1
            ;;
        *)
            die "Unrecognized argument $1 (-help for usage)"
            ;;
    esac
    shift
done

if [ "X$tarball" = "X" ] ; then
    die "No tarball specified (-help for usage)"
fi

case "$tarball" in
    /*)
        ;;
    *)
        tarball=`pwd`/$tarball
        ;;
esac

namespace=`echo $USER | tr a-z A-Z`_TEST
base_dir=$HOME/gx-map-$namespace
if [ -d $base_dir ] ; then
    die "Directory $base_dir already exists"
fi
try mkdir $base_dir
try cd $base_dir

source_dir=`basename $tarball .tar.gz`
if [ -d $source_dir ] ; then
    die "Directory $source_dir already exists"
fi
try tar zxf $tarball
try cd $source_dir

install_dir=$base_dir/gx-map-$namespace-install
data_dir=$base_dir/gx-map-$namespace-data

cat <<EOF > $namespace.conf
PERL                     $perl
PATH                     $path
NAMESPACE                $namespace
INSTALL_DIR              $install_dir
DATA_DIR                 $data_dir
REQUESTS_LOG_PERMISSIONS 444
GLOBUS_ADMINS            $USER
ADMIN_EMAIL              $USER@sdsc.edu
EOF

try ./configure-gx-map $namespace.conf
try make install
try cd ..
try rm -rf $source_dir

try mkdir $base_dir/grid-security
try mkdir $base_dir/grid-security/certificates

cat <<EOF
# ======================================================================
# Add the following cron commands (adjust frequency to taste).
#
# minute hour mday month wday command
#
* * * * * $install_dir/sbin/gx-check-requests -namespace $namespace ; $install_dir/sbin/gx-gen-mapfile $base_dir/grid-security/grid-mapfile ; $install_dir/sbin/gx-gen-mapfile -dump -all $base_dir/grid-security/gx-map-dump
* * * * * $install_dir/sbin/gx-ca-update -target-dir $base_dir/grid-security/certificates -ca ... -ca ...
# ======================================================================
EOF
