#!/bin/sh

# $Id: make-release,v 1.22 2006-05-24 19:36:55-07 kst Exp $
# $Source: /home/kst/gx-map-redacted/make-release,v $

try() {
    echo "% $@"
    eval "$@" || exit 1
}

if [ $# -eq 0 ] ; then
    num=`./get-version`
elif [ $# -eq 1 ] ; then
    case "$1" in
        [0-9]*)
            num=$1
            ;;
        *)
            echo "Usage: $0 [num]" 1>&2
            exit 1
            ;;
    esac
else
    echo "Usage: $0 [num]" 1>&2
    exit 1
fi

if [ "$num" = "" ] ; then
    echo "Error getting version" 1>&2
    echo "Usage: $0 [num]" 1>&2
    exit 1
fi

in_files=`ls *.in | grep -v gx-map.conf.in`
other_files="INSTALL LICENSE Makefile README README.TeraGrid \
             README.Upgrade Relnotes cleanup-gx-map configure-gx-map \
             gx-check-prereqs gx-propagate.in.teragrid \
             gx-propagate.in.test sample.conf test-gx-map tgcdb.db-config"

# cadesc_files=`cd ca ; echo *.cadesc`
# bug_files=`cd bugs ; echo bug-*`

if [ -f release/gx-map-$num.tar.gz ] ; then
    echo "release/gx-map-$num.tar.gz already exists" 1>&2
    exit 1
fi

try mkdir release/gx-map-$num
try cd release/gx-map-$num

for file in $in_files ; do
    try cp -p ../../$file .
done
for file in $other_files ; do
    try cp -p ../../$file .
done

try mkdir ca
try cd ca
ls ../../../ca | grep '\.cadesc$' | \
    while read file ; do
        try cp -p ../../../ca/$file .
    done
try cd ..

try mkdir bugs
try cd bugs
ls ../../../bugs | grep '^bug-....$' | \
    while read file ; do
        try cp -p ../../../bugs/$file .
    done
try cd ..

try mkdir doc
try cd doc
ls ../../../doc | grep '\.pod$' | \
    while read file ; do
        try cp -p ../../../doc/$file .
    done
try cd ..

try cd ..
try tar zcf gx-map-$num.tar.gz gx-map-$num
try rm -rf gx-map-$num
