#!/bin/sh

# $Id: make-release,v 1.30.2.1 2007-03-02 01:27:46-08 kst Exp $
# $Source: /home/kst/gx-map-redacted/make-release,v $

try() {
    echo "% $@"
    eval "$@" || exit 1
}

usage() {
    echo "Usage: $0 [-help] [-cadesc filename] [version]"
    exit 1
}

today=`date +%Y-%m-%d`

cadesc_flag=0
got_version=0
for arg in "$@" ; do
    if [ "$arg" = "-h" -o "$arg" -eq "-help" ] ; then
        usage()
    elif [ $cadesc_flag -eq 1 ] ; then
        cadesc_tarball="$arg"
        $cadesc_flag=0
    elif [ $arg = "-cadesc" ] ; then
        cadesc_flag=1
    else
        version="$arg"
    fi
done

if [ "$version" = "" ] ; then
    version=`./get-version`
fi

if [ "$version" = "" ] ; then
    echo "Error getting version" 1>&2
    usage()
fi

if [ -f release/gx-map-$version.tar.gz ] ; then
    echo "release/gx-map-$version.tar.gz already exists" 1>&2
    exit 1
fi

cadesc_tarball=gx-map-cadesc-$today.tar.gz
if [ -f release/$cadesc_tarball ] ; then
    echo ">>> Using existing $cadesc_tarball"
else
    try ./make-cadesc-release
fi

in_files=`ls *.in | grep -v gx-map.conf.in`
other_files="INSTALL LICENSE Makefile README README.TeraGrid \
             README.Upgrade Relnotes auto.txt cleanup-gx-map \
             configure-gx-map gettimeofday.c gx-check-prereqs \
             gx-propagate.in.teragrid gx-propagate.in.test \
             patch-gx-map-0.5.3.2 \
             sample-gx-cron-job.conf sample.conf test-gx-map \
             tgcdb.db-config"

try mkdir release/gx-map-$version
try cd release/gx-map-$version

for file in $in_files ; do
    try cp -p ../../$file .
done
for file in $other_files ; do
    try cp -p ../../$file .
done

try cp -p ../$cadesc_tarball .

try mkdir bugs
try cd bugs
ls ../../../bugs | grep '^bug-....$' | \
    while read file ; do
        try cp -p ../../../bugs/$file .
    done
try cd ..

try mkdir doc
try cd doc
ls ../../../doc | grep '\.pod$' | \
    while read file ; do
        try cp -p ../../../doc/$file .
    done
try cd ..

try cd ..
try tar zcf gx-map-$version.tar.gz gx-map-$version
try rm -rf gx-map-$version
