#!/bin/sh

# $Id: make-cadesc-release,v 1.3 2007-07-11 18:32:44-07 kst Exp $
# $Source: /home/kst/gx-map-redacted/make-cadesc-release,v $

try() {
    echo "% $@"
    eval "$@" || exit 1
}

try_quietly() {
    if [ $verbose -eq 1 ] ; then
        echo "% $@"
    fi
    eval "$@" || exit 1
}

old=0
force=0
verbose=0

for arg in "$@" ; do
    case "$arg" in
        -old)
            old=1
            ;;
        -force)
            force=1
            ;;
        -verbose)
            verbose=1
            ;;
        *)
            echo "Usage: $0 [-old] [-force] [-verbose]" 1>&2
            exit 1
            ;;
    esac
done

today=`date +%Y-%m-%d`

dir=gx-map-cadesc-$today
tarball=gx-map-cadesc-$today.tar.gz

if [ -d release/$dir ] ; then
    if [ $force = 1 ] ; then
        try rm -rf release/$dir
    else
        echo "release/$dir already exists" 1>&2
        exit 1
    fi
fi

if [ -f release/$tarball ] ; then
    if [ $force = 1 ] ; then
        try rm -f release/$tarball
    else
        echo "release/$tarball already exists" 1>&2
        exit 1
    fi
fi

try mkdir release/$dir
try cd release/$dir
echo "... Copying *.cadesc files"
ls ../../ca | grep '\.cadesc$' | \
    while read file ; do
        if [ $old = 1 ] ; then
            if egrep '^(CERTIFICATE_FORM|CRL_FORM)' ../../ca/$file >/dev/null 2>&1 ; then
                echo "Skipping $file"
            else
                echo $file
                sed '/^SIGNED_BY *self$/s/^/# /;/^CERT_BEGINS/s/^/# /' ../../ca/$file > $file
            fi
        else
            try_quietly cp -p ../../ca/$file .
        fi
    done

cat >README <<EOF
This directory contains a number of *.cadesc files, used by the
gx-ca-update command, part of the gx-map package.  Each file contains
information about a certificate authority.  See the gx-map-cadesc(5)
man page.

These files are installed automatically as part of gx-map.  You can
use the gx-install-cadesc command to install an updated set of *.cadesc
files; see the gx-install-cadesc(8) man page for more information.

This release of the *.cadesc files was built $today.
EOF

try cd ..
try tar zcf $tarball $dir
try rm -rf $dir
