#!/usr/bin/perl

# $Id: decorate,v 1.1 2007-10-09 15:56:01-07 kst Exp $
# $Source: /home/kst/gx-map-redacted/ca/Attic/decorate,v $

use strict;
use warnings;

my $hash = undef;
my $status = undef;

open my $PIPE, '|-', 'checksums';

while (<>) {
    print $PIPE $_;
    if (/^HASH\s+([\da-f]{8})\b/) {
        $hash = $1;
    }
    if (/^## status\s+=\s+(\w+)/) {
        $status = $1;
    }
}

print $PIPE '=' x 72, "\n";
# print "hash = $hash\n";
# print "status = $status\n";

print $PIPE `cert-info -ca $hash .igtf-1.16/igtf-policy-installation-bundle-1.16/src/$status/$hash.0`;

close $PIPE;
