#!/usr/bin/perl

# $Id: decorate,v 1.4 2007-10-09 20:38:46-07 kst Exp $
# $Source: /home/kst/gx-map-redacted/ca/Attic/decorate,v $

use strict;
use warnings;

my $igtf_version = '1.17';
my $igtf_src_dir = ".igtf-$igtf_version/igtf-policy-installation-bundle-$igtf_version/src";

my $hash = undef;
my $status = undef;

open my $PIPE, '|-', 'checksums';

while (<>) {
    print $PIPE $_;
    if (/^HASH\s+([\da-f]{8})\b/) {
        $hash = $1;
    }
#   if (/^## status\s+=\s+(\w+)/) {
#       $status = $1;
#   }
}

print $PIPE '=' x 72, "\n";

if (not defined $hash) {
    print $PIPE ">>> No hash found\n";
    close $PIPE;
    exit;
}

my $command = "cert-info -ca $hash";

my $igtf_info_file = undef;

if (opendir my $DIR, $igtf_src_dir) {
    my @subdirs = sort grep { $_ ne '.' and $_ ne '..' } readdir $DIR;
    foreach my $subdir (@subdirs) {
        if (-e "$igtf_src_dir/$subdir/$hash.0") {
            $command .= " $igtf_src_dir/$subdir/$hash.0";
        }
        if (-e "$igtf_src_dir/$subdir/$hash.info") {
            $igtf_info_file = "$igtf_src_dir/$subdir/$hash.info";
        }
    }
    closedir $DIR;
}

print $PIPE `$command`;

if (defined $igtf_info_file) {
    print $PIPE "# The following is a copy of $hash.info from the IGTF $igtf_version release:\n";
    open my $INFO, '<', $igtf_info_file;
    while (<$INFO>) {
        print $PIPE "## $_";
    }
    close $INFO;
}

close $PIPE;
