# $Id: gx-map-requests-log.5.pod,v 1.1 2005-12-29 18:34:01-08 kst Exp $
# $Source: /home/kst/gx-map-redacted/doc/gx-map-requests-log.5.pod,v $

=head1 NAME

gx-map requests.log - The F<requests.log> file format used by B<gx-map>

=head1 DESCRIPTION

The F<requests.log> file is used by the B<gx-map> system to store
information about requests for updates to the B<grid-mapfile>.  It's a
plain text file consisting a sequence of requests.  Each request
consists of a line containing only an opening brace '{', a sequence of
lines each containing an attribute name followed by the corresponding
attribute value, and a line consisting only of a closing brace '}'.

The file is stored in the F<var> subdirectory of the B<gx-map>
installation directory.

More details to follow when I update this man page.

=head1 SEE ALSO

gx-map(7), gx-request(1), gx-check-requests(8), gx-gen-mapfile(8)

=head1 AUTHOR

Keith Thompson, San Diego Supercomputer Center, <kst@sdsc.edu>

=head1 COPYRIGHT AND LICENSE

See the file F<LICENSE> in the B<gx-map> distribution, installed in
the F<etc> subdirectory.
